apiVersion: v1
entries:
  mariadb:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 10.6.8
    created: "2023-02-17T17:33:42.827002598+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: MariaDB is an open source, community-developed SQL database server
      that is widely in use around the world due to its enterprise features, flexibility,
      and collaboration with leading tech firms.
    digest: 91fe0e4ea7c5eda4ed590f0eb866de5b0d3f563ca5247032ae2f11f4f32ec934
    home: https://github.com/bitnami/charts/tree/master/bitnami/mariadb
    icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
    keywords:
    - mariadb
    - mysql
    - database
    - sql
    - prometheus
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: mariadb
    sources:
    - https://github.com/bitnami/bitnami-docker-mariadb
    - https://github.com/prometheus/mysqld_exporter
    - https://mariadb.org
    urls:
    - https://iraangeles.github.io/helm-nextcloud/charts/mariadb-11.0.14.tgz
    version: 11.0.14
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 14.4.0
    created: "2023-02-17T17:33:42.830403206+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 0f28a70ea01674fe9754f442b81499cafd60bb5c3b9255dd95bd285a83f7a60a
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/containers/tree/main/bitnami/postgresql
    - https://www.postgresql.org/
    urls:
    - https://iraangeles.github.io/helm-nextcloud/charts/postgresql-11.6.26.tgz
    version: 11.6.26
  redis:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 6.2.7
    created: "2023-02-17T17:33:42.835165298+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: aa28e953e8e7f56d473c06823cabad79538cf9a2e66b3d582929753afd3aa18f
    home: https://github.com/bitnami/charts/tree/master/bitnami/redis
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    urls:
    - https://iraangeles.github.io/helm-nextcloud/charts/redis-16.12.3.tgz
    version: 16.12.3
generated: "2023-02-17T17:33:42.82337797+08:00"
